# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

global:
  filters:
  - number: 1007
  - number: 1015
  - number: 58
  - number: 107

import:
- file: JLCPCB
  definitions:
    _KIBOT_MANF_DIR: Manufacturers/JLCPCB
    _KIBOT_POS_PRE_TRANSFORM: '[''_kicost_rename'', ''_rot_footprint'']'
    _KIBOT_BOM_ENABLED: 'false'
- file: PCBWay
  definitions:
    _KIBOT_MANF_DIR: Manufacturers/PCBWay

preflight:
  drc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV
  # This PCB is not a real circuit so skip erc
  # erc:
  #   dont_stop: true
  #   format: HTML,RPT,JSON,CSV

outputs:
- name: basic_excellon
  comment: Drill files in EXCELLON format
  type: excellon
  dir: Gerbers_and_Drill
  options:
    map: pdf
- name: basic_gerb_drill
  comment: Drill files in GERB_DRILL format
  type: gerb_drill
  dir: Gerbers_and_Drill
  options:
    map: gerber
- name: gerber_modern
  comment: Gerbers in modern format, recommended by the standard
  type: gerber
  dir: Gerbers_and_Drill
  layers:
  - layer: F.Cu
    suffix: F_Cu
    description: Front copper
  - layer: B.Cu
    suffix: B_Cu
    description: Bottom copper
  - layer: User.Drawings
    suffix: User_Drawings
    description: User drawings
  - layer: Edge.Cuts
    suffix: Edge_Cuts
    description: Board shape
- name: basic_info
  comment: Information about the run
  type: info
  dir: .
- name: basic_navigate_results
  comment: Web page to browse the results
  type: navigate_results
  dir: Browse
  options:
    link_from_root: index.html
    skip_not_run: true
- name: basic_pcb_print_pdf
  comment: PCB
  type: pcb_print
  dir: PCB/PDF
  options:
    format: PDF
    pages:
    - layers:
      - layer: F.Cu
      - layer: Edge.Cuts
      - layer: User.Drawings
      sheet: Front copper
    - layers:
      - layer: B.Cu
      - layer: Edge.Cuts
      - layer: User.Drawings
      mirror: true
      sheet: Bottom copper
    keep_temporal_files: true
- name: report_simple
  comment: Simple design report
  type: report
  output_id: _simple
  options:
    template: simple_ASCII
- name: report_full
  comment: Full design report
  type: report
  options:
    template: full_SVG

...
definitions:
  _KIBOT_MANF_DIR_COMP: Manufacturers
  _KIBOT_GERBER_LAYERS: "- layer: 'F.Cu'\n        suffix: 'F_Cu'\n        description:\
    \ 'Front copper'\n      - layer: 'B.Cu'\n        suffix: 'B_Cu'\n        description:\
    \ 'Bottom copper'\n      - layer: 'Edge.Cuts'\n        suffix: 'Edge_Cuts'\n \
    \       description: 'Board shape'"
